id: P010453
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-19 20:50:39.575846
source_metadata:
  id: bdr:W1KG4857
  title: འཚོ་བྱེད་སྨན་པའི་ལམ་གྱི་རིམ་པ་ཆུང་ངུ
  author: ''
  volumes:
    9bc23c1b024e4148844802f315097ef1:
      image_group_id: I1KG5015
      title: ''
      volume_number: 1
      total_pages: 414
      base_file: v001.txt
    d8760ead0d8f49d586826a83070fed20:
      image_group_id: I1KG5016
      title: ''
      volume_number: 2
      total_pages: 214
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
